# Ward — verify-gated model routing for local coding agents.
#
# `make` (build) + `make test` + `make install` is the release gate; the
# version is stamped from git at build time so every binary can name its
# provenance (`ward version`).

BINARY  := ward
PKG     := .
MODULE  := github.com/mha-home-lab/ward

VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
LDFLAGS := -X $(MODULE)/internal/cli.Version=$(VERSION)

GOPATH_DIR := $(shell go env GOPATH 2>/dev/null || echo $$HOME/go)
BINDIR ?= $(GOPATH_DIR)/bin
DESTDIR :=

.PHONY: all build test fmt vet install uninstall check clean

all: build

## build: compile ./ward with the git-derived version stamp
build:
	go build -ldflags '$(LDFLAGS)' -o $(BINARY) $(PKG)

## test: run the full test suite
test:
	go test ./...

## fmt: rewrite non-conforming formatting in place; prints any stragglers
fmt:
	gofmt -w .
	@gofmt -l .

## vet: go vet over every package
vet:
	go vet ./...

## install: build then place the binary on PATH ($GOPATH/bin, override BINDIR=)
install: build
	mkdir -p $(DESTDIR)$(BINDIR)
	install -m 0755 $(BINARY) $(DESTDIR)$(BINDIR)/$(BINARY)

## uninstall: remove the installed binary
uninstall:
	rm -f $(DESTDIR)$(BINDIR)/$(BINARY)

## check: the full verification gate (fmt clean + vet + tests)
check: fmt vet test
	@test -z "$$(gofmt -l .)" || { echo 'gofmt -l . not empty:'; gofmt -l .; exit 1; }

## clean: remove build artifacts and task workflows generated by runs
clean:
	rm -f $(BINARY)
